/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResultTypeIdRouteImport } from './routes/result/$typeId'
import { Route as QuizQuestionIdRouteImport } from './routes/quiz/$questionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultTypeIdRoute = ResultTypeIdRouteImport.update({
  id: '/result/$typeId',
  path: '/result/$typeId',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizQuestionIdRoute = QuizQuestionIdRouteImport.update({
  id: '/quiz/$questionId',
  path: '/quiz/$questionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/quiz/$questionId': typeof QuizQuestionIdRoute
  '/result/$typeId': typeof ResultTypeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/quiz/$questionId': typeof QuizQuestionIdRoute
  '/result/$typeId': typeof ResultTypeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/quiz/$questionId': typeof QuizQuestionIdRoute
  '/result/$typeId': typeof ResultTypeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/quiz/$questionId' | '/result/$typeId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/quiz/$questionId' | '/result/$typeId'
  id: '__root__' | '/' | '/quiz/$questionId' | '/result/$typeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  QuizQuestionIdRoute: typeof QuizQuestionIdRoute
  ResultTypeIdRoute: typeof ResultTypeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result/$typeId': {
      id: '/result/$typeId'
      path: '/result/$typeId'
      fullPath: '/result/$typeId'
      preLoaderRoute: typeof ResultTypeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$questionId': {
      id: '/quiz/$questionId'
      path: '/quiz/$questionId'
      fullPath: '/quiz/$questionId'
      preLoaderRoute: typeof QuizQuestionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  QuizQuestionIdRoute: QuizQuestionIdRoute,
  ResultTypeIdRoute: ResultTypeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
